// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Prime.Backend.Data;
using System;

namespace Prime.Backend.Migrations
{
    [DbContext(typeof(MessageRecordContext))]
    partial class MessageRecordContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("Prime.Backend.Data.MessageRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ComponentName");

                    b.Property<byte[]>("DataBinary");

                    b.Property<string>("DataString");

                    b.Property<bool>("IsBinary");

                    b.Property<int>("MessageCommand");

                    b.Property<string>("MessageTimestamp");

                    b.Property<string>("SourceIP");

                    b.HasKey("Id");

                    b.ToTable("MessageRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
